backend:
  name: github
  repo: ywass/watermenplumbing-gatsby
  branch: branch-name
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/images
public_folder: /images

collections:   
  - label: "Home Page"
    name: "homepage"
    files:    
    - label: "Home Page"
      name: "home"
      file:  "src/data/pages/home/index.json"   
      media_folder: ''
      public_folder: ''         
      fields:
        - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "home",
          }
        - { label: Title, name: title, widget: string, required: false } 
        - label: Meta Data
          name: meta
          widget: "object"
          fields:
            - {label: Seo Title, name: seoTitle, widget: string, required: false}
            - {label: Seo Description, name: seoDescription, widget: text, required: false} 
            - {label: Seo Keywords, name: seoKeywords, widget: text, required: false}  
  - name: "pages"
    label: "Pages"
    folder: "src/data/pages"
    media_folder: ''
    public_folder: ''    
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "pages",
        }
      - { label: Title, name: title, widget: string, required: false } 
      - { label: Slug, name: slug, widget: string, required: false }   
      - { label: Content, name: content, widget: markdown, required: false }        
      - label: Meta Data
        name: meta
        widget: "object"
        fields:
          - {label: Seo Title, name: seoTitle, widget: string, required: false}
          - {label: Seo Description, name: seoDescription, widget: text, required: false} 
          - {label: Seo Keywords, name: seoKeywords, widget: text, required: false} 
  - name: "areasweservepages"
    label: "Areas We Serve Pages"
    folder: "src/data/pages/areasweserve/"
    media_folder: ''
    public_folder: ''    
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "areasweservepages",
        }
      - { label: Title, name: title, widget: string, required: false } 
      - { label: Slug, name: slug, widget: string, required: false }         
      - label: Meta Data
        name: meta
        widget: "object"
        fields:
          - {label: Seo Title, name: seoTitle, widget: string, required: false}
          - {label: Seo Description, name: seoDescription, widget: text, required: false} 
          - {label: Seo Keywords, name: seoKeywords, widget: text, required: false} 
  - name: "plumbingservices"
    label: "Plumbing Services"
    folder: "src/data/pages/plumbingservices/"
    media_folder: ''
    public_folder: ''    
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "plumbingservices",
        }
      - { label: Title, name: title, widget: string, required: false } 
      - { label: Slug, name: slug, widget: string, required: false }         
      - label: Meta Data
        name: meta
        widget: "object"
        fields:
          - {label: Seo Title, name: seoTitle, widget: string, required: false}
          - {label: Seo Description, name: seoDescription, widget: text, required: false} 
          - {label: Seo Keywords, name: seoKeywords, widget: text, required: false} 
  - name: "waterfilterproducts"
    label: "Water Filter Products"
    folder: "src/data/pages/waterfilterproducts/"
    media_folder: ''
    public_folder: ''    
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "waterfilterproducts",
        }
      - { label: Title, name: title, widget: string, required: false } 
      - { label: Slug, name: slug, widget: string, required: false }         
      - label: Meta Data
        name: meta
        widget: "object"
        fields:
          - {label: Seo Title, name: seoTitle, widget: string, required: false}
          - {label: Seo Description, name: seoDescription, widget: text, required: false} 
          - {label: Seo Keywords, name: seoKeywords, widget: text, required: false}
  - name: "blog"
    label: "Blog"
    folder: "src/data/blog"
    media_folder: ''
    public_folder: ''    
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: Title, name: title, widget: string }  
      - { label: Slug, name: slug, widget: string }
      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'blogcategory'
        search_fields: ['categoryname']
        value_field: 'categoryname'
        display_fields: ['{{categoryname}}']
        multiple: true
      - label: Meta Data
        name: meta
        widget: "object"
        fields:
          - {label: Seo Title, name: seoTitle, widget: string}
          - {label: Seo Description, name: seoDescription, widget: string}  
          - {label: Seo Keywords, name: seoKeywords, widget: text, required: false}    
      
         
  - name: "blogcategory"
    label: "Category"
    folder: "src/data/blogcategory"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
       - { label: Name, name: categoryname, widget: string }
       - label: Meta Data
         name: meta
         widget: "object"
         fields:
            - {label: Seo Title, name: seoTitle, widget: string}
            - {label: Seo Description, name: seoDescription, widget: string}  
            - {label: Seo Keywords, name: seoKeywords, widget: text, required: false}    
 
      